### ISSUE TITLE
Bedrijven terrein AnyLogic interface op holon model zetten

### ISSUE THREAD

**Issue by naudloomans** [ZEnMo/Digital-twin-Drechtsteden#13]

**Comment by naudloomans** [comment]
Nog te doen:

- [ ] Jaarsimulatie 'headless'; model-state tijdelijk opslaan om jaarsimulatie mogelijk te maken. Of zou het beter werken om alle agent-populaties te clonen en zo een losstaand model te runnen? Of zelfs een 'echt' headless model te instantieren? -> alleen states opslaan.
- [ ] Berekening aandeel duurzame energie/elektriciteit in totale energieconsumptie (nu tijdelijk vervangen door zelfvoorzienendheid. Is berekening aan eind van simulatie voldoende, of willen we dit elke tijdstap berekenen?) -> Berekening eind vd simulatie voldoende, we gaan voor altijd simulaties berekenen na aanpassing input.
- [ ] Actoren + contracten instantieren bij aanmaken gridconnections. (nodig voor prijsgestuurd gedrag en accounting van geldstromen)
- [ ] Warmte-assets toevoegen aan verblijfsobjecten (zowel consumptie als conversie/productie warmteassets ( warmtevraag profiel, gasbrander, warmtepomp)
- [ ] Energiebalans/netbelasting grafiek werkend maken (vergt ook accounting van actueel energieverbruik en opwek tijdens modelrun! Energy assets uitbreiden met energyUsed_kWh, energyProduced_kWh, currentConsumption_kW en currentProduction_kW?

- [ ] Naud doet dit :Uitlijnen van 'groups' met sliders en dergelijke -> lage prioriteit want nog onzeker welke sliders nodig zijn.
- [ ] Grafieken per energiedrager; stroom, gas, warmte, waterstof, ... (niet samen in 1 grafiek!)
- [ ] UI opschonen, grafische elementen (TU/e logo, paarse balk bovenaan, etc.) herstellen.
- [ ] Berekening CO2 uitstoot adhv geimporteerde energiedragers.


Gedaan:

-  Draaiend model met data uit excel files ipv holon-jsons.
-     GIS-kaart waarop gebouwen, trafo's, netkabels en 'regions' getekend worden en waarop geclickt kan worden.
-     Utility gridconnections aanmaken adhv residence_objects-database.
-     Profieldata gebruiken voor residence_objects waar die beschikbaar is (adhv company_connection_id) (standaard profiel voor rest van verblijfsobjecten)
-     Grafieken van verbruik en productie van elektriciteit op het bedrijventerrein werkend.
-     Slider voor PV op dak werkend (maar gebruikt nog geen data over beschikbaar dakoppervlak)
-     GridNodes aanmaken adhv trafo-data. (en 1 hardcoded HSMS trafo voor totale vermogen van het gebied)
-     Grafieken per bedrijf plotten als je op een gebouw op de kaart clickt (alleen elektriciteit)


Voorlopig niet
- Berekening gebiedskosten

**Comment by GillisHommen** [comment]
- [ ] Sliders werkend maken voor: EVs/trucks, windturbines, verwarmingstype (gasketel vs warmtepomp).
- [ ] Slider en gedrag buurtbatterij maken
