### ISSUE TITLE
Neighborhood of GISNeighborhood als agent of javaclass

### ISSUE THREAD

**Issue by naudloomans** [ZEnMo/Digital-twin-Drechtsteden#17]

**Comment by GillisHommen** [comment]
GIS_Area agent toegevoegd, met OL_AreaType die type NEIGHBORHOOD, BUSINESS, INDUSTRY of HVTRANSFORMER kan hebben. (kan nog uitgebreid worden).

OL_AreaType vervangt OL_SimulatedArea
