### ISSUE TITLE
Workshop voorbereiden

### ISSUE THREAD

**Issue by petertue** [ZEnMo/Digital-twin-Drechtsteden#19]
- Nieuwe visuele componenten laten zien
- Huidige Drechtsteden model gebruiken
- Up-to-date plan multi-level presenteren

**Comment by GillisHommen** [comment]
Wat bedoel je precies? :)

**Comment by petertue** [comment]
Lijstje met punten moeten we aanvullen as we go. Nieuw model gebruiken zei naud in de meeting, maar bedoelde hij uiteindelijk wat anders mee. Dus die zal ik er zo uit halen

**Comment by naudloomans** [comment]
Deze workshop / meeting is geweest
