### ISSUE TITLE
Aantal trucks en bestelwagen data in model zetten / aan model koppelen

### ISSUE THREAD

**Issue by petertue** [ZEnMo/Digital-twin-Drechtsteden#22]
Roosmarijn stuurde een dashboard van overmorgen over bedrijven op: https://overmorgen.maps.arcgis.com/apps/dashboards/1322e878a71443f588cfd3594483b871

Daarin staan aantal trucks en bestelwagens (weet niet hoe goed data is). Dit kunnen we aan het model koppelen.

Eerst even bespreken met Erik of we niet al data hierover hebben en wat beste koppelmethode is.

**Comment by naudloomans** [comment]
Aan Roosmarijn vragen of zij bij RDW statistieken van bedrijfswagens (busjes en trucks) per buurt kan opvragen

**Comment by naudloomans** [comment]
Gedaan met NAL database
