### ISSUE TITLE
Stappen webpagina's nieuw bedrijventerrein uploaden

### ISSUE THREAD

**Issue by naudloomans** [ZEnMo/Digital-twin-Drechtsteden#54]

**Comment by naudloomans** [comment]
Welke stappen gaan we moeten nemen qua webpagina's en modellen om snel de modellen te repliceren

**Comment by GillisHommen** [comment]
Doel is om met één anylogic model verschillende bedrijventerreinen te kunnen modelleren. (waar we nu nog steeds een nieuw model aanmaken, en al die modellen ook steeds net andere implementaties en UIs hebben)
