### ISSUE TITLE
Warmtevraag berekening verbeteren

### ISSUE THREAD

**Issue by naudloomans** [ZEnMo/Digital-twin-Drechtsteden#56]

**Comment by naudloomans** [comment]
- [ ] Warmtevraag o.b.v. gasprofiel als deze is aangeleverd
- [ ] Warmtevraag o.b.v. bedrijventerrein totaal uitsplitsen naar individuele bedrijven. Evt samenvoegen van methode o.b.v. vloeroppervlak met totaal.

Statistieken totaal verbruik

[_business_parks.xlsx](https://github.com/ZEnMo/Digital-twin-Drechtsteden/files/13333659/_business_parks.xlsx)

**Comment by GillisHommen** [comment]
Voor Groote Lindt ontbreekt gasverbruik van in de klimaatmonitor. Wel is gasvebruik van gemeente zwijndrecht beschikbaar.

Voor Groote Lindt is het opgeteld vebruik van alle profiel-aansluitingen hoger dan het electriciteitsverbruik dat in de klimaatmonitor staat voor 2019. 

Data lijkt dus onvolledig en/of achterhaald.
Ik heb wel een implementatie gemaakt die de afwijking van het totale gas- en elektriciteitsverbruik t.o.v. klimaatmonitorwaardes corrigeert door de niet-profiel-aansluitingen te schalen. De aansluitingen waarvan we profieldata hebben blijft dus ongemoeid.

**Comment by naudloomans** [comment]
@GillisHommen Kan je met deze beter uit de voeten https://www.cbs.nl/nl-nl/maatwerk/2021/41/energielevering-aan-bedrijven-per-wijk-2019-2020
