### ISSUE TITLE
Totaal aantal elektrische trucks voor bedrijventerrein model uit NAL database halen

### ISSUE THREAD

**Issue by naudloomans** [ZEnMo/Digital-twin-Drechtsteden#57]

**Comment by naudloomans** [comment]
- [ ] Set max voor aantal trucks en andere bedrijfswagens o.b.v. NAL analyse. Moet wel overschreven worden als de som van trucks aangeleverd door de bedrijven groter is dan opgenomen in deze analyse

[_neighborhoods_vehicles.xlsx](https://github.com/ZEnMo/Digital-twin-Drechtsteden/files/13333729/_neighborhoods_vehicles.xlsx)

**Comment by GillisHommen** [comment]
Er is nog geen rittenpatroon voor bestelbusjes beschikbaar. Op dit moment gebruik ik hetzelfde rittenpatroon als voor trucks, maar met een lager energieverbruik per kilometer.
Er is ook geen data voor het totaal aantal personenwagens, alleen het aantal elektrische personenwagens. Ik heb voor nu nog geen personenwagens toegevoegd.
