### ISSUE TITLE
1ste ontwerp KPI's als meters

### ISSUE THREAD

**Issue by naudloomans** [ZEnMo/Digital-twin-Drechtsteden#58]

**Comment by naudloomans** [comment]
Meters

    Aandeel lokaal opgewekt (taartgrafiek)
    Verbruik per categorie (taartgrafiek)
    Aandeel netgebruik
    Dag/nacht balans (uitgebalanceerd is groen, verschillen zijn rood)
    Weekgrafiek balans (uitgebalanceerd is groen, verschillen zijn rood)
    Jaargrafiek balans uitgebalanceerd is groen, verschillen zijn rood)
    Verdelingsgrafiek (10% duurste uren heeft 50% van de piekvraag)

**Comment by GillisHommen** [comment]
(ik val in herhaling, maar ik zet hier toch nog even mijn mening neer over 'aandeel lokaal opgewekt'. ;) )
In plaats van aandeel lokaal opgewekt, zou ik absolute waardes van opgewekte- en verbruikte energie laten zien, bijvoorbeeld als staafdiagrammen. 
Die twee getallen kun je niet tegen elkaar wegstrepen, omdat ze niet per see dezelfde energiedrager en niet per see gelijktijdig zijn. Je kunt bijvoorbeeld door heel veel PV te plaatsen een hoog 'aandeel lokaal opgewekt' krijgen, terwijl de netbelasting alleen maar toeneemt, en de zelfvoorzienendheid (vrijwel) niet stijgt.
De ratio van die twee getallen wordt nu 'aandeel lokaal opgewekt' genoemd, maar het is niet het aandeel van de lokaal verbruikte energie die lokaal is opgewekt. Het aandeel van de lokaal gebruikte energie die ook lokaal is opgewekt, is wat we nu de zelfvoorzienendheid noemen. Misschien is het beter om gewoon de zelfvoorziendheid te laten zien in een taartgrafiek. 
Volgens mij zorgt dit 'aandeel lokaal opgewekt' vooral voor verwarring en geeft het de verkeerde indruk. Het wordt in feite als zelfvoorzienendheid geinterpreteerd, waardoor er verkeerde conclusies uit getrokken worden. 
We zouden ook nog de term 'aandeel lokaal opgewekt' in stand kunnen houden, maar hier de waarde van zelfvoorzienendheid voor gebruiken.

**Comment by GillisHommen** [comment]
Beginnetje 

![Image](https://github.com/ZEnMo/Digital-twin-Drechtsteden/assets/98752265/092eb68c-27fd-4685-af33-8cd883c18e11)

**Comment by GillisHommen** [comment]
Tweede versie (in voorbereiding op L4L demonstratie, netbelastingduurkromme hernoemd naar Onbalansduurkromme)

![Image](https://github.com/ZEnMo/Digital-twin-Drechtsteden/assets/98752265/66bb4720-e278-469a-974b-132dddf75cc3)

**Comment by GillisHommen** [comment]
De bovenste grafiekjes geven denk ik goed in 1 oogopslag de verhouding tussen totale opwek, totaal verbruik, en de overlap van die twee; de zelfconsumptie.

![Image](https://github.com/ZEnMo/Digital-twin-Drechtsteden/assets/98752265/d6f7d288-8721-4d8c-8951-b7ef2efdc5d9)

**Comment by naudloomans** [comment]
Kunnen we deze maandag bespreken met Roosmarijn en Jory

**Comment by GillisHommen** [comment]
Na gesprek Roosmarijn 6 dec, idee om resultaten op verschillende niveaus van diepgang te presenteren.

**Voorstel 1ste niveau:**
Zelfvoorzienendheid [%] -> Evt ook als indicator voor duurzaamheid gebruiken
Netbelasting: overbelastingsduur [uur] (eventueel overbelastingsuren van meerdere trafo's optellen)

Energiebalans jaarlijks:
Totale opwek [MWh]
Totaal verbruik [MWh]
Totaal zelfverbruik [MWh]

**Voorstel 2e niveau:**
Energiebalansen per seizoen, week/weekend, dag/nacht, ...
Flex-behoefte [MWh] -> 'Overbelastingsvolume' -> Dit is ook in de energiebalans-barplot te verwerken!

**Voorstel 3e niveau:**
Netbelastingsduurkromme met indicatie van netcapaciteit
Gemiddelde absolute netbelasting [%]
Load-factor (piek / gemiddelde netbelasting)

**Comment by naudloomans** [comment]
Na gesprek met klankbordgroep 14/12

Alle niveau's aan de hand van vragen.

**Niveau 1 = samenvatting**
Aan de hand van 2 hoofdvragen:
1. Lokaal opgewekt en zelfvoorzienendheid - percentages en jaargemiddelde belasting
2. Netbelasting - Uren overbelasting, max overbelasting, evt. grafiek van dag met max overbelasting teruglevering en levering

**Niveau 2 =  subvragen**
Nog te bepalen maar iig:

- Belastingduurkrommes
- Energiebalans per tijdseenheid
- vraag / aanbod grafieken met daarin netbelasting
- Handreikingen richting oplossingsrichtingen

**Algemeen**

- Altijd selectie gebied en energiedrager in beeld voor overzich

**Comment by GillisHommen** [comment]
Na klankbordgroepmeeting 14 dec, verdere verfijning van resultaatweergave.
Huidige status plus opmerkingen:

### Live simulatie
Lopende grafieken van vraag en aanbod, eventueel selectie van energiedragers. (checkboxes?)

### KPI's samenvattend
Zelfvoorzienendheid [%] -> Proberen uit te leggen dat dit eigenlijk het 'aandeel <van lokaal energieverbruik dat> lokaal is opgewekt' is, waar nu vaak onterecht de verhouding totale opwek en totale verbruik wordt genomen. 
Eventueel vervangen door Duurzaamheid [%] adhv de duurzaamheid van de gebruikte energiedragers. (dit zal overigens niet veel afwijken van het percentage zelfvoorzienendheid)
Netbelasting: overbelastingsduur [uur] (eventueel overbelastingsuren van meerdere trafo's optellen), misschien ook hoogte van piek?

**Feedback:** Kleurtjes van KPI-circles kan verwarrend zijn als dezelfde kleuren in de bar-plots terugkomen. Ook is kleur een subjectief waardeoordeel.

Energiebalans jaarlijks:
Totaal zelfverbruik gebied [MWh]
Totale import, opgedeeld in energiedragers[MWh]
Totaal export (wsl alleen stroom) [MWh]
Deze barplots geven ook totaal verbruik en totale opwek (waaruit je de 'boekhoudkundige' (maar betekenisloze!) KPI 'aandeel lokaal opgewekt' zou kunnen berekenen. 

Eventueel kijken of jaarlijkse opweg grafiek erbij past. (al zou je jaarlijkse vraag dan ook willen laten zien vind ik)

### KPI's gedetailleerd:
**Vraag/aanbod**
Vraag/aanbod grafieken van verschillende periodes.

**Energiebalansen**
Energiebalansen per seizoen, week/weekend, dag/nacht, ...
Flex-behoefte [MWh] -> 'Overbelastingsvolume' -> Dit is ook in de energiebalans-barplot te verwerken, ook verdeeld in overbelasting door tekorten en overbelasting door overschot.

**Netbelasting**
Netbelastingsduurkrommes (van verschillende periodes) 
Gemiddelde absolute netbelasting [%]
Load-factor (piek / gemiddelde netbelasting)


### Voorstel voor verfijning
Grafieken indelen op hoofdvraag, ofwel welke vragen willen we beantwoorden en welke grafieken geven daarvoor het beste inzicht?
Vragen kunnen zijn:
-Hoe verhoog ik mijn duurzaamheid/verlaag ik mijn CO2 uitstoot?
-Wat is er mogelijk wbt ruimte/congestie op het E-net? -> Welke vorm van flex/besparing/buffering kan hier voor verbetering zorgen?
-...

**Comment by naudloomans** [comment]
@GillisHommen Zullen we na de sessie van vandaag kijken of we deze issue op kunnen knippen in een paar kleine cocnrete taken die we ook daadwerkelijk kunnen afronden als 1ste ontwerp

**Comment by GillisHommen** [comment]
ja, goed plan!

**Comment by GillisHommen** [comment]
Status ten tijde van 'done':


![Image](https://github.com/ZEnMo/Digital-twin-Drechtsteden/assets/98752265/f2009f90-50c3-4d09-afe3-534e7ee931f0)

DIt is niet het definitieve ontwerp, maar hierop wordt doorgeborduurd.
