### ISSUE TITLE
Navragen certificering / documentatie AL en Energieke Regio rondom informatiebeveiliging

### ISSUE THREAD

**Issue by naudloomans** [ZEnMo/Digital-twin-Drechtsteden#61]
- [ ] AnyLogic
- [ ] Energieke Regio

**Comment by Erikvv** [comment]
Energieke regio gemaild. Ik heb ook overwogen Comsi te mailen maar leek me niet zo nuttig gezien hun beperkte rol.

**Comment by Erikvv** [comment]
AnyLogic gemaild

**Comment by Erikvv** [comment]
AnyLogic geeft aan dat ze geen gecertificeerd framework gebruikt en verwijst naar de privacy policy voor details.

**Comment by naudloomans** [comment]
@Erikvv  had je al reactie van energieke regio?

**Comment by naudloomans** [comment]
@Erikvv Kan deze issue geclosed worden? Is volgens mij gebeurt en we hebben hierop een plan voor databeveiliging toch
