### ISSUE TITLE
Pv potentie op 100% doet praktisch niets op MS niveau

### ISSUE THREAD

**Issue by petertue** [ZEnMo/Digital-twin-Drechtsteden#8]
Als de slider van pv op 100% staat wordt er alsnog helemaal niets terug geleverd op MS niveau. Misschien is dat correct in een stad. Maar moeten we even valideren.

Door een run te doen en een MS station te selecteren kun je het zien.

![image](https://github.com/ZEnMo/Digital-twin-Drechtsteden/assets/97597063/2b3cfe4f-074b-4bb3-bc5f-8c74d100575c)

**Comment by naudloomans** [comment]
Is gefixt met data uit zonnedakje
